path:
  ckpt_path: "/mnt/hdd_storage/di_fit_tts_output/ckpt/Fitted_v19_flowv2"
  log_path: "/mnt/hdd_storage/dfit/logs/Findv19"
  result_path: "/mnt/hdd_storage/dfit/output/Findv19"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 16
  warm_up_step: 100000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 10000000
  log_step: 500
  synth_step: 25000
  val_step: 25000
  save_step: 50000
  mid_output : 10000
