path:
  ckpt_path: "/mnt/hdd_storage/di_tts_output/ckpt/Fitted_v18_flowv2"
  log_path: "/mnt/hdd_storage/di_tts_output/logs/Fitted_v18_flowv2"
  result_path: "/mnt/hdd_storage/di_tts_output/output/Fitted_v18_flowv2"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 16
  warm_up_step: 100000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 50000000
  log_step: 1000
  synth_step: 1000
  val_step: 2000
  save_step: 10000
